student={1:"abhinav",2:"pmna"}
student
type(student)
id(student)
dir(student)
student[2]
student[1]
students={"name":"abhinav","dob":"20/11/2003","address":"manakkal"}
students
students["address"]
students["dob"]
students.keys()
students.values()
students.items()
students["age"]
students["age"]=21
students["age"]=56
students
students.get("adress")
students.update({"name":"shaz","dob":"12/12/12,"})
students